# -*- coding: utf-8 -*-
"""NUMPY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRqCFPwJNvwnUpHJtZVTgasVFqF5w5Ag
"""

# Numpy --> Numerical Python

import numpy
import numpy as np

print(numpy.__version__)

# numpy provides the support for most powerful data structure -- array

arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

numbers = list(range(1,1001))
total = 0
for i in numbers:
  total = total + i
print(total)

# Python List vs Numpy

# how much execution time will be taken by List and sum()
import time
numbers = list(range(1,100000001))
total = 0
start_time = time.time()  # record start time
for i in numbers:
  total = total + i
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")
#.4f means show 4 digits after the decimal point

numbers = np.arange(1,100000001)
total = 0
start_time = time.time()  # record start time
total = np.sum(numbers)
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")

# array()
# In programming, an array is a data structure used to store collection of data values

# Arrat : Single Dimension(1D) and Multi Dimensional (2D)

# How to create array (1D)

arr = np.array([10,20,30,40,50,60])
print(type(arr))
print(arr)

# An array is a collection of SIMILAR DATA TYPE

emp_info = np.array([123,'Yash',45.24,True])
print(emp_info)

# Shape property
# used to determine the dimension of an array
# For 1D array return (n,) --> where n is the number of elemens
# For 2D array return (n,m) --> where n is the number of rows and m is the number of columns

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr)

arr = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
print(arr.shape)
print(arr)

# Indexing and Slicing

arr = np.array([10,20,30,40,50,60])
# 10  20  30  40  50  60
# 0   1   2   3   4   5
# -6  -5  -4  -3  -2  -1

print(arr)
print(arr[-1])
print(arr[3])
print(arr[1:5])
print(arr[::-1])

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[1,2])
print(arr[2,2])

# show the first row only
print(arr[0])

print()

# show the second column only   FOR COLUMN USE THIS SYNTAX [:,COLUMN_INDEX_NUMBER]
print(arr[:,1])

print()

# show only first 2 rows
print(arr[0:2])
print()
print(arr[:,1:])  # print c1 and c2 only

# Numpy Data Types
arr = np.array([10,20,30,40,50,60])
print(arr.dtype)
# dtype property helps us to determine the data type of an array

arr = np.array([10.1,20.2,30.3,40.4,])
print(arr.dtype)

arr = np.array([True,False,False,True])
print(arr.dtype)

arr = np.array(['A','B','C',''])
print(arr.dtype)

arr = np.array(['Anas','Nexperts Academy','C','D'])
print(arr.dtype)

arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.nbytes) # total bytes used by an array

# we can also use dtype for Conversion

arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.nbytes) # total bytes used by an array

# this int64 means 64 Bits
# meaning each and every individual element of an array can take upto 64 bits
# we have 4 elements
# 4 * 64 Bits --> Total Size Of Arr : 256 bits
# and if we convert it into bytes  4 element * 8 bytes  : 32 bytes


# behind the scene each and every individual element will gonna take 64 digits space

# 6bits 6*4 ==> 24 bits
#  Total Size Of Arr :24 bits

arr = np.array([10,20,30,40],dtype='i1')
print(arr.dtype)
print(arr.nbytes)

arr = np.array([10,20,30,40],dtype='i1')
print(arr.dtype)
print(arr.nbytes)

# this int8 means 8 Bits
# meaning each and every individual element of an array can take upto 8 bits
# we have 4 elements
# 4 * 8 Bits --> Total Size Of Arr : 32 bits
# and if we convert it into bytes  4 element * 1 bytes  : 4 bytes

# behind the scene each and every individual element will gonna take 8 digits space


# real life example when in an array, you are storing the age or marks

age = np.array([34,78,56,21,90,100,120,17],dtype='i2')
print(age.dtype)
print(age.nbytes)

# i1 --> 8 digits space
# i2 --> 16 digits space
# i4 --> 32 digits space
# i8 --> 64 digits space

a = np.array([10,20,30,40],dtype='f')
print(a)
print(a.dtype)

a = np.array([10. , 20. , 30., 40.],dtype='i')
print(a)
print(a.dtype)

# astype() used for conversion
arr = np.array([10. , 20. , 30. , 40.])
arr = arr.astype('i8')
print(arr.dtype)

# copy() vs view() method of Numpy

# copy()
# a copy will create a new independent array in a different memory location
# usually when want to share with junior dev

ori_array = np.array([1,2,3,4,5,6])
print(ori_array)

copy_array = ori_array.copy()
print(copy_array)

# if we make any changes in copied array, it won't affect the original array
copy_array[0] = 100
print(copy_array)
print(ori_array)

# view
# a view is the representation of the origial array
# the original array will be affected when the view is edited. Usually sharing with other senior dev

ori_array = np.array([1,2,3,4,5,6])
print(ori_array)

copy_array = ori_array.view()
print(copy_array)

# if we make any changes in copied array, it will affect the original array
copy_array[0] = 100
print(copy_array)
print(ori_array)

# if we make any changes in ori array, it will affect the copy array
ori_array[4] = 400
print(ori_array)
print(copy_array)

ori_array = np.array([1,2,3,4,5,6])
copy_array = ori_array.view()

# shares_memory() --> return True if arrays are sharing the same memory location

print(np.shares_memory(ori_array,copy_array))

# Numpy Array Reshaping
# converting 1D into 2D or converting 2D into 1D
# reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)

print()

arr = arr.reshape(4,3)
print(arr)

print()

print(arr.shape)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr.shape)  # 13x1

# numpy.newaxis is used to increase the dimension of the existing array by one more dimension
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# arr[:,np.newaxis]            Column Vector
arr = arr[np.newaxis,:]      # Row Vector
print(arr.shape)
print(arr)

# numpy.newaxis (Column vector)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
arr = arr[:,np.newaxis]           # Column Vector

print(arr.shape)
print(arr)

# Converting 2D to 1D

twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(6)
print(arr)

twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(-1)
print(arr)

twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.flatten()
print(arr)

# concatenate()
# used to join or merges 2 arrays

price1 = np.array([20,60,80,45,32])
price2 = np.array([10,20,30,40,50,60,80,45,32])
arr = np.concatenate((price1,price2))
print(arr)

t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((t1,t2))
print(arr)

# array_split()
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr = np.array_split(arr,3)
print(arr[0])
print(arr[1])
print(arr[2])

# sorting
# np.sort() by default it will sort in ascending order

prices = np.array([25,43,114,359,24,7,54,94,55])

print(np.sort(prices))

# descending order sort

prices = np.array([25,43,114,359,24,7,54,94,55])

print(np.sort(prices)[::-1])  # descending order

# Filter and searching in an array

prices = np.array([25,43,114,359,24,7,54,94,55])
print(prices)

for i in prices:
  if i>=50:
    print(i)

prices = np.array([25,43,114,359,24,7,54,94,55])
# Boolean Masking
prices>=50

prices = np.array([25,43,114,359,24,7,54,94,55])
# Boolean Masking
newprices = prices[prices>=50]  # here we are applying a filter prices [showMeOnlyTrueValues]
print(newprices)

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# show the even number prices
newprices = prices[prices%2==0]
print(newprices)

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# show the even number prices
prices%2==0 , prices>=50

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# np.where(expression)
# np.where return INDEX NUMBERS
np.where(prices%2==0)

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
# np.where(expression)
# np.where return INDEX NUMBERS
res = np.where(prices%2==0)
print(prices[res])

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
res = np.where((prices%2==0) & (prices>=50))
print(prices[res])

# & combine both conditions

prices = np.array([78,34,56,90,102,34,12,67,172,120,95,45])
print(prices[(prices%2==0) & (prices>=50)])  # & combine both conditions

# SALARY CLASSIFICATION
salary = np.array([25000, 40000, 55000, 70000, 30000, 90000])
# Replace salary with High if salary >= 60000
# Replace salary with Medium if salary >= 40000 and <= 60000
# Otherwise Low

# np.where(condition,value_if_true,value_if_false)

result = np.where(
    salary >= 60000 , "High" ,
    np.where(salary >=40000 , "Medium" ,"Low")
)

print(result)

salary = np.array([25000, 40000, 55000, 70000, 30000, 90000])

res = np.where(salary>=60000,'High',np.where(salary>=40000,'Medium','Low'))

print(res)

# Numpy Random Module
from numpy import random
x = random.randint(100) # 1 till 100
print(x)

x = random.randint(100,150) # # 100 till 150
print(x)

# rand() generate random float
# method return a random float value between 0 and 1

print(random.rand())

arr = random.rand(10)
print(arr)

arr = random.rand(5,4)
print(arr)

# generating 1D array

arr = random.randint(30,120,size=(5)) # size means dimension of an array
print(arr)

# generating 2D array
arr = random.randint(30,120,size=(3,4)) # size means dimension of an array
print(arr)

# choice() method allow you to generate random value
# base on an array of values

arr = random.choice([10,20,30,40,50,60])
print(arr)

arr = random.choice([10,20,30,40,50,60],size=(7))
print(arr)

arr = random.choice([10,20,30,40,50,60],size=(3,4))
print(arr)

# numpy.zeros()
# this function allows us to create an array filled with zeros
# default data type will be float

x = np.zeros(7)
print(x)

x = np.zeros((3,3),dtype='i')
print(x)

# numpy.ones()
# this function allows us to create an array filled with Ones
# default data type will be float

x = np.ones(7)
print(x)

# numpy.sum()
# used to compute the sum of all element

x = np.random.randint(50,size=(50))
print(x)

print('Sum of an array')
print(np.sum(x))

# numpy.mean()
# mean value is the average value
print('Mean of an array')
print(np.mean(x))

print('Min of an array')
print(np.min(x))

print('Max of an array')
print(np.max(x))

# numpy.unique()
# return unique elements as a sorted array
a = np.array([1,2,3,11,4,10,9,12,5,6,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
print(np.unique(a))

# Answer in 1 2 3 11 4 10 9 12 5 6 7 8

a = np.array([1,2,3,11,4,10,9,12,5,6,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv , i = np.unique(a,return_index=True)
print(uv)
print(i)
# return_index --> it will print the index numbers

# argsort --> reorder the index numbers in a proper sequence
uv[np.argsort(i)]

a = np.array([1,2,3,11,4,10,9,12,5,6,4,3,2,5,6,7,8,9,2,3,4,5,7,1])
uv , i = np.unique(a,return_index=True)
uv[np.argsort]

# arange
print(np.arange(10))
print(np.arange(1,11))
print(np.arange(1,11,2))

# Numpy Broadcasting
arr1 = np.array([16,24,26])
arr2 = np.array([13,22,19])

print(arr1+arr2)
print(arr1*arr2)

arr1 = np.array([16,24,26,12])
arr2 = np.array([13,22,19])

print(arr1+arr2)

# in which cases there will be no broadcasting error
# case 1 : when arrays element are equal
# case 2 : if any element is 1

arr1 = np.array([16,24,26])
arr2 = np.array([2])

print(arr1+arr2)