# -*- coding: utf-8 -*-
"""PANDAS_part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URQ2Alb25invv_r1iC3mw4jM5_XqUIw8
"""

import numpy as np
import pandas as pd

print(pd.__version__)

# numpy --> array()
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr)

# Pandas Series
# Series is 1D labelled array

s = pd.Series([10,20,30,40,50])
print(type(s))
print(s)
print(s.shape)

# in numpy --> Only numbers
# in Series --> Numbers + Labels (index)

info = pd.Series(['John',28,6700,'Klang'],index = ['name','age','sal','city'])
                                              # meaningful keyname index
print(info)
print(info['name'])       # indexing
print(info.get('city'))   # getting data values using get()
print(info.iloc[0])       # iloc --> index location

# Series is like a Dictionary + array combo

# values property
# print only values

print(info.values)

# Indexing Slicing and using for loop
s = pd.Series([100,200,300,400,500,600],index=['v1','v2','v3','v4','v5','v6'])
print(s)

# 100 200 300 400 500 600
#  0   1   2   3   4   5
# -6  -5  -4  -3  -2  -1
# v1  v2  v3  v4  v5  v6

# indexing in Series can be done by using [] or iloc[] or loc[]
print('\nIndexing in Series')
print(s.iloc[2])    # for index numbers
print(s.loc['v5'])  # loc use for labes
print(s['v2'])      # [] used for labels
print(s.iloc[-1])

print('\nSlicing in Series')
print(s[1:4])         # 4 will be excluded --> stopIndex
print(s['v1':'v5'])   # if performing slicing using labels, the end label is included

# print 100 400 600

print('\nFor specific information')
print(s[['v1','v4','v6']])    # for specific information s[['','','']]
print(s[['v1','v4','v6']].values)

# conditional selection

print('\nConditional Selection')
print(s[s%3==0])

# using for loop

for i in s:
  print(i)

for k,v in s.items():
  print(k,v)

for i in enumerate(s):
  print(i)

# Pandas DataFrame
# it is used to display the information in a tabular fashion
# Pandas DataFrame is 2D array

data = {
    'name':['John','Alex','Smith'],
    'dept':['IT','HR','MR'],
    'sal':[6700,5600,6000],
    'city':['KL','JB','ML']
}
print(data)

df = pd.DataFrame(data)
print(df)   # print(df) or df
df

print(df.shape)

data = {
    'Calories':[420,380,560],
    'Duration':[56,30,75]
}
df = pd.DataFrame(data,index=['Day1','Day2','Day3',])
df

df['Calories']

df['Calories'].values

print(df['Calories'].values)

# perform selection

df.loc['Day1']

# perform multiple selection

df.loc[['Day1','Day3']]

# Using Pandas to deal with diff diff file formats
    # Read an excel file
    # Read an csv file
    # Read a txt file
    # Read json file
    # Upload local files
    # Read a sql file

# Read an excel file
# read_excel()

data = pd.read_excel('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
data

# ExcelFile()
# in order to get the data from a different sheet

excelfile  = pd.ExcelFile('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
excelfile.sheet_names

data = pd.read_excel(excelfile,'Sheet2')
data

# CSV --> comma separated values
# read_csv()

data = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv')
data

# read a txt file @ tab-delimited file
# reading the content of excel file saved with .txt format

data = pd.read_csv('https://raw.githubusercontent.com/prefuse/Prefuse/refs/heads/master/data/fisher.iris.txt',sep='\t')
data

# read a json file
# read_json()

data = pd.read_json('https://raw.githubusercontent.com/yash240990/Python/master/simple.json')
data

# Upload local files in colab

from google.colab import files
uploaded = files.upload()   # files selection wizard

data = pd.read_csv('testdata.csv')
data

# 17/3/26 part 1 pandas , part 2 will be continued