# -*- coding: utf-8 -*-
"""SEABORN_ANAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQFTXJ2qNoAGlUZJrI1T7srBHakiPxEt
"""

# SEABORN DATA VISUALIZATION LIBRARY

import warnings
warnings.filterwarnings('ignore')  # used to ignore warnings

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

print(sns.__version__)

# built-in datasets of seaborn
sns.get_dataset_names()

dataset = sns.load_dataset('iris')
dataset

# Line Graph
# lineplot()
sns.lineplot(x='sepal_length', y='sepal_width', data=dataset)
plt.title('Lineplot in Seaborn')
plt.show()

# adding style to seaborn
plt.figure(figsize=(10,5))
sns.set_style('whitegrid',{'grid.color':'lightblue','grid.linestyle':'--'}) # -- dashed : dotted  - solid
sns.lineplot(x='sepal_length', y='sepal_width', data=dataset)
plt.title('Line plot in Seaborn', color='red', fontsize='10')
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.show()

pokemon = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/pokemon.csv')
pokemon

# scatterplot()
sns.scatterplot(x='Attack',y='Defense',data=pokemon)
plt.title('Scatterplot in Seaborn')
plt.show()

pokemon.Generation.value_counts()

pokemon.Generation.value_counts().sort_index()

sns.scatterplot(x='Attack',y='Defense',hue='Generation',data=pokemon)
plt.title('Scatterplot in Seaborn')
plt.show()

colors = ['r','y','b','g','c','m']
sns.scatterplot(x='Attack',y='Defense',hue='Generation',palette=colors,data=pokemon)
plt.title('Scatterplot in Seaborn')
plt.show()

# lmplot()
# used to generate a scatter plot with a regression line

colors = ['r','y','b','g','c','m']
sns.lmplot(x='Attack',y='Defense',hue='Generation',palette=colors,data=pokemon)
plt.title('Scatterplot in Seaborn')
plt.show()

# countplot()
# used to generate a bar graph

plt.figure(figsize=(15,5))
sns.countplot(x='Type 1',data=pokemon)
plt.title('Countplot in Seaborn')
plt.show()

pokemon['Type 1'].value_counts()

pkmn_type_colors = ['#3ae40c',  # Grass
                    '#e52106',  # Fire
                    '#0AE3D6',  # Water
                    '#A8B820',  # Bug
                    '#A8A878',  # Normal
                    '#A040A0',  # Poison
                    '#F8D030',  # Electric
                    '#E0C068',  # Ground
                    '#EE99AC',  # Fairy
                    '#C03028',  # Fighting
                    '#F85888',  # Psychic
                    '#B8A038',  # Rock
                    '#705898',  # Ghost
                    '#98D8D8',  # Ice
                    '#ECF709',  # Dragon
                    '#7A786C',  # Dark
                    '#D3D1C0',  # Steel
                    '#91E8EE',  # Flying
                   ]

plt.figure(figsize=(15,5))  # increase figure size
sns.countplot(x='Type 1',palette=pkmn_type_colors,data=pokemon)
plt.title('Countplot in Seaborn')
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x='Type 1',palette=pkmn_type_colors,data=pokemon)
plt.title('Countplot in Seaborn')
plt.xticks(rotation=45) # use xticks(rotation)
plt.show()

dataset = sns.load_dataset('tips')
dataset

sns.relplot(x='total_bill',y='tip',col='sex',hue='day',data=dataset)
plt.show()

sns.relplot(x='total_bill',y='tip',col='time',hue='smoker',data=dataset)
plt.show()

# Heatmap
# A heatmap is a colored table where colors represent data values,
# helping to quickly identify high, low, positive, or negative values.

'''
Common places where heatmaps are used:

1. Correlation Analysis (Very common in data science)

To show relationships between variables

Example:

Study hours vs marks

Features in machine learning datasets

Helps spot strong positive or negative relationships quickly

2. Academic Performance / Education

Student scores across subjects

Attendance vs performance

Identifying strong and weak areas

3. Website & App Analytics

To see where users click or spend time

Mouse movement or scrolling behavior

Dark areas = more user activity

4. Business & Sales Analysis

Sales performance by region and time

Product demand across months

High and low revenue zones

'''

data = {
    'Hours_Studied':[2,3,4,5,6,7,8],
    'Marks_Scored':[40,50,60,70,80,90,100],
    'TV_Watched':[10,9,8,6,7,5,3]
}

df = pd.DataFrame(data)
df

corr = df.corr()
corr

sns.heatmap(corr,cmap='viridis',annot=True) # 'viridis','coolwarm','Blues'
plt.title('Heatmap')
plt.show()

